# Setup
title:            Portfolio
tagline:          'A Jekyll theme'
description:      'Hello, my name is Rebecca also known around the Internet as Immortallisk.'
url:              https://hyde.getpoole.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
