# Setup
title:            Portfolio
tagline:          'A Jekyll theme'
description:      'Hello, my name is Rebecca also known around the Internet as Immortallisk.'
paginate:         5

# About and contact
author:
  name:           'Rebecca 'Immortallisk' Sauerlender'
  url:            https://twitter.com/Immortallisk
  

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

