# Setup
title:            Becca's Designs
tagline:          'A Portfolio'
description:      'Rebecca Sauerlender. <br> Simplicity and Functionality'
paginate:         5

# About and contact
author:
  name:           'Rebecca Sauerlender'
  url:            https://twitter.com/Immortallisk
  

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

